---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: monitor
  namespace: kube-system
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: jmutai-admin
          containers:
          - name: monitor
            image: gowrisankar22/kubebox:latest
            command:
            - /bin/bash
            - -c
            - monitor
          restartPolicy: OnFailure
