---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default
          containers:
          - name: monitor
            image: bitnami/kubectl:latest
            command: [ "/bin/sh" ]
            args: [ "/opt/bitnami/kubectl/bin/monitor" ]
          restartPolicy: OnFailure
